### ISSUE TITLE
String interpolation in shell commands doesn't work

### ISSUE THREAD

**Issue by onnimonni** [rubys/ruby2js#41]
I have an example folder structure like this:
```
$ tree
.
├── folder\ with\ spaces
│   └── test.txt
└── thing.rb
```

`test.txt` contains only 1 line: `Hello world!`.

The ruby file `thing.rb` looks like this
```ruby
def system_call_example
  path = 'folder with spaces/test.txt'
  puts `cat '#{path}'`
end

system_call_example()
```
If I run the script with ruby I see:
```
$ ruby thing.rb
Hello world!
```

I'm using a custom helper to convert ruby to javascript named `ruby2js`:
```ruby
#!/usr/bin/env ruby
require 'ruby2js/filter/return'
require 'ruby2js/filter/require'
require 'ruby2js/filter/functions'
require 'ruby2js/filter/node'
require 'ruby2js'

input_file = ARGV[0]
output_file = ARGV[1]

if File.exists?(input_file)
  javascript = Ruby2JS.convert(File.read(input_file),
    file: input_file,
    eslevel: 2017,
    strict: true,
    filters: [
      Ruby2JS::Filter::Return,
      Ruby2JS::Filter::Require,
      Ruby2JS::Filter::Functions,
      Ruby2JS::Filter::Node
    ]
  )
  if output_file
    File.open(output_file, 'w') { |file| file.write(javascript)}
  else
    puts javascript
  end
end
```

When I try to convert earlier ruby example to javascript it fails:
```bash
$ bundle exec ./bin/ruby2js thing.rb thing.js
NameError: undefined local variable or method `accumulator' for #<#<Class:0x00007ff5e54d2dc0>:0x00007ff5e54d2cf8>
  /Users/onni.hakala/Projects/ruby-serverless/gems/ruby2js/lib/ruby2js/filter/node.rb:327:in `on_xstr'
  /Users/onni.hakala/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ast-2.4.0/lib/ast/processor/mixin.rb:259:in `process'
  /Users/onni.hakala/Projects/ruby-serverless/gems/ruby2js/lib/ruby2js.rb:86:in `process'
  /Users/onni.hakala/Projects/ruby-serverless/gems/ruby2js/lib/ruby2js/filter/node.rb:24:in `process'
  /Users/onni.hakala/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ast-2.4.0/lib/ast/processor/mixin.rb:276:in `block in process_all'
  /Users/onni.hakala/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ast-2.4.0/lib/ast/processor/mixin.rb:275:in `map'
  /Users/onni.hakala/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ast-2.4.0/lib/ast/processor/mixin.rb:275:in `process_all'
  /Users/onni.hakala/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/parser-2.5.3.0/lib/parser/ast/processor.rb:164:in `on_send'
  /Users/onni.hakala/Projects/ruby-serverless/gems/ruby2js/lib/ruby2js.rb:135:in `on_send'
  /Users/onni.hakala/Projects/ruby-serverless/gems/ruby2js/lib/ruby2js/filter/node.rb:269:in `on_send'
  /Users/onni.hakala/Projects/ruby-serverless/gems/ruby2js/lib/ruby2js/filter/functions.rb:358:in `on_send'
  /Users/onni.hakala/Projects/ruby-serverless/gems/ruby2js/lib/ruby2js/filter/require.rb:67:in `on_send'
  /Users/onni.hakala/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ast-2.4.0/lib/ast/processor/mixin.rb:259:in `process'
  /Users/onni.hakala/Projects/ruby-serverless/gems/ruby2js/lib/ruby2js.rb:86:in `process'
  /Users/onni.hakala/Projects/ruby-serverless/gems/ruby2js/lib/ruby2js/filter/node.rb:24:in `process'
  /Users/onni.hakala/Projects/ruby-serverless/gems/ruby2js/lib/ruby2js/filter/functions.rb:226:in `on_send'
  /Users/onni.hakala/Projects/ruby-serverless/gems/ruby2js/lib/ruby2js/filter/require.rb:67:in `on_send'
  /Users/onni.hakala/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ast-2.4.0/lib/ast/processor/mixin.rb:259:in `process'
  /Users/onni.hakala/Projects/ruby-serverless/gems/ruby2js/lib/ruby2js.rb:86:in `process'
  /Users/onni.hakala/Projects/ruby-serverless/gems/ruby2js/lib/ruby2js/filter/node.rb:24:in `process'
  /Users/onni.hakala/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ast-2.4.0/lib/ast/processor/mixin.rb:276:in `block in process_all'
  /Users/onni.hakala/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ast-2.4.0/lib/ast/processor/mixin.rb:275:in `map'
  /Users/onni.hakala/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ast-2.4.0/lib/ast/processor/mixin.rb:275:in `process_all'
  /Users/onni.hakala/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/parser-2.5.3.0/lib/parser/ast/processor.rb:11:in `process_regular_node'
  /Users/onni.hakala/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ast-2.4.0/lib/ast/processor/mixin.rb:259:in `process'
  /Users/onni.hakala/Projects/ruby-serverless/gems/ruby2js/lib/ruby2js.rb:86:in `process'
  /Users/onni.hakala/Projects/ruby-serverless/gems/ruby2js/lib/ruby2js/filter/node.rb:24:in `process'
  /Users/onni.hakala/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ast-2.4.0/lib/ast/processor/mixin.rb:276:in `block in process_all'
  /Users/onni.hakala/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ast-2.4.0/lib/ast/processor/mixin.rb:275:in `map'
  /Users/onni.hakala/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ast-2.4.0/lib/ast/processor/mixin.rb:275:in `process_all'
  /Users/onni.hakala/Projects/ruby-serverless/gems/ruby2js/lib/ruby2js/filter/return.rb:20:in `on_def'
  /Users/onni.hakala/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ast-2.4.0/lib/ast/processor/mixin.rb:259:in `process'
  /Users/onni.hakala/Projects/ruby-serverless/gems/ruby2js/lib/ruby2js.rb:86:in `process'
  /Users/onni.hakala/Projects/ruby-serverless/gems/ruby2js/lib/ruby2js/filter/node.rb:24:in `process'
  /Users/onni.hakala/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ast-2.4.0/lib/ast/processor/mixin.rb:276:in `block in process_all'
  /Users/onni.hakala/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ast-2.4.0/lib/ast/processor/mixin.rb:275:in `map'
  /Users/onni.hakala/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ast-2.4.0/lib/ast/processor/mixin.rb:275:in `process_all'
  /Users/onni.hakala/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/parser-2.5.3.0/lib/parser/ast/processor.rb:11:in `process_regular_node'
  /Users/onni.hakala/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ast-2.4.0/lib/ast/processor/mixin.rb:259:in `process'
  /Users/onni.hakala/Projects/ruby-serverless/gems/ruby2js/lib/ruby2js.rb:86:in `process'
  /Users/onni.hakala/Projects/ruby-serverless/gems/ruby2js/lib/ruby2js/filter/node.rb:26:in `process'
  /Users/onni.hakala/Projects/ruby-serverless/gems/ruby2js/lib/ruby2js.rb:170:in `convert'
  /Users/onni.hakala/Projects/ruby-serverless/bin/ruby2js:13:in `<top (required)>'
```

I'm using latest version of the gem from the github with bundler.

**Comment by rubys** [comment]
Perhaps this is a misfeature, but from the README:

> expressions enclosed in backtick operators (``) and %x{} literals are evaluated in the context of the caller and the results are inserted into the generated JavaScript. See https://github.com/rubys/ruby2js/blob/master/lib/ruby2js/converter/xstr.rb

The reason for this feature is that my original target for this was the browser which has no ability to shell out to commands, and I had a need to insert values from the server's environment into the result.

Perhaps we could have a filter (or option?) that converts :xstr into `child_process.exec_sync`?  Meanwhile, there is a node filter that will handle `system` calls.

**Comment by onnimonni** [comment]
I'm not sure if I can follow what you're saying.

I might be stupid here but:
Why can't we just find the pattern `#{}` from the ruby string and replace it with `${}`?

> Perhaps we could have a filter (or option?) that converts :xstr into child_process.exec_sync? Meanwhile, there is a node filter that will handle system calls.

If it helps I think we should add an option to `Ruby2JS.convert` where user can explicitly choose whether to build for nodejs or browser

**Comment by onnimonni** [comment]
In addition I think that currently if user require the node module:
```ruby
require 'ruby2js/filter/node'
```
It's kind of explicit that they want code that works in the server.

**Comment by rubys** [comment]
I think you are mixing two things.

Both Ruby and JavaScript have string interpolation.  If you use double quoted strings in Ruby and have embedded `#{}` these strings will be converted into back-tic quotes strings in JavaScript using `${}`, presuming that you have specified a target of es2015 or later (see https://github.com/rubys/ruby2js/blob/718e345cd8765d457b426f57cca1f8985007eb31/spec/es2015_spec.rb#L95).

Ruby also has the ability to shell out to system commands using either `system` or backtics.  The node filter will handle calls to `system`, but does not currently handle backtics.  It could, but doing so would lose access to the feature where such strings are evaluated in either the context of the caller (or  alternately, using the binding that they pass as an option).  See https://github.com/rubys/ruby2js/blob/718e345cd8765d457b426f57cca1f8985007eb31/spec/transliteration_spec.rb#L1013

**Comment by jaredcwhite** [comment]
Grooming the backlog…looks like we can close this.
