### ISSUE TITLE
Sprockets > 4 throws undefined method `register_engine'

### ISSUE THREAD

**Issue by buhrmi** [rubys/ruby2js#68]
I think `register_engine` was deprecated some time ago and is now gone in Rails 6.

```
`block in <class:Engine>': undefined method `register_engine' for #<Sprockets::Environment:0x00005602c1be63a0> (NoMethodError)
Did you mean?  register_pipeline
```

**Comment by buhrmi** [comment]
Offending line: https://github.com/rubys/ruby2js/blob/master/lib/ruby2js/rails.rb#L50

This is how sass-rails fixed it: https://github.com/rails/sass-rails/commit/0faab4dc78db930ab63780a79be9cc837a2b1fbd

**Comment by jaredcwhite** [comment]
Thanks @buhrmi for the pointer. Looks like we should be able to make a similar fix.

**Comment by buhrmi** [comment]
A bit off-topic, but what are your thoughts on a webpacker integration since it's the default now for new rails projects?

**Comment by rubys** [comment]
@buhrmi good job identifying a fix; did it work for you?  Would it be possible for you to create a pull request?

**Comment by jaredcwhite** [comment]
Hey @buhrmi I forgot to mention there _is_ a Webpacker integration now: https://github.com/whitefusionhq/rb2js-loader

I've started using it on a couple projects now (eating my own dogfood) and it's working pretty nicely.

**Comment by buhrmi** [comment]
Hi @rubys, I didn't spend time on trying to fix sprockets. Since Webpacker is the default javascript bundler in Rails now, I'm trying to get that to work. Currently getting an error tho:

```
Module build failed (from ./node_modules/rb2js-loader/dist/cjs.js):
Error: /home/buhrmi/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ruby2js-3.4.0/lib/ruby2js/serializer.rb:366:in `sourcemap': undefined method `expression' for nil:NilClass (NoMethodError)
        from /home/buhrmi/simpwars/rb2js.config.rb:28:in `process_with_source_map'
        from -e:1:in `<main>'
```

Not sure why, will investigate. When the rb2js-loader is working fine, IMHO that should be the new default way to integrate rb2js with Rails.

**Comment by rubys** [comment]
Can you try the following change?

```diff
diff --git a/lib/ruby2js/serializer.rb b/lib/ruby2js/serializer.rb
index 912c8d7..06a6f09 100644
--- a/lib/ruby2js/serializer.rb
+++ b/lib/ruby2js/serializer.rb
@@ -363,7 +363,7 @@ module Ruby2JS

       @sourcemap = {
         version: 3,
-        file: @ast.loc.expression.source_buffer.name,
+        file: @ast.loc&.expression.source_buffer.name,
         sources: sources.map(&:name),
         mappings: @mappings
       }
```

**Comment by buhrmi** [comment]
Or, maybe not. Because when I actually want to use a class compiled with rb2js-loader, I have to explicitly call `export` INSIDE the .rb file. This prevents me from using that file server-side. My main use case for rb2js is to share code between server and client

**Comment by jaredcwhite** [comment]
Ah, yeah that's the Achilles' heel of the webpack approach. Just spitballing here, but you might be able to solve it by adding the export statement manually at the bottom of the file and including a server-only export method that's a no-op. (same thing for imports)

**Comment by rubys** [comment]
I made some progress on the original issue, but there is more work to be done.  For starters, I updated the code to the latest Sprockets API.  That eliminated the stack traceback, but the `.js.rb` files are not being picked up.  I took a look at how coffee script did it, an added a few more statements, but no luck.  I then tried to get coffee-script itself working, and couldn't get it to work.  I've committed what I've done so far, so it can be picked back up later.

What would be most helpful right now is for someone to describe a scenario that works for them with coffeescript, and I can look into getting the same scenario working with ruby2js.

**Comment by hmdne** [comment]
You can take a look at how we do the Sprockets integration in Opal. I was a person who did this upgrade and you can take a look at the commit history:

https://github.com/opal/opal-sprockets/blob/master/lib/opal/sprockets/processor.rb

(And this pull request, which ultimately got squashed: https://github.com/opal/opal-sprockets/pull/19/commits)

From my first look, I don't think you want to use `register_preprocessor`, it's for a different purpose, for example for parsing Sprockets directives. Additionally the API has changed and I don't really know how this code could work now (maybe Rails does something). Engines used to call some sort of (Tilt-compatible) `#render` (maybe `#call`?) API if I'm not mistaken, but transformers do `.call`.

The problem may also depend on the mime types you are using. Looking at the directives that Sprockets use: https://github.com/rails/sprockets/blob/master/lib/sprockets.rb you are more likely to make a success by using `application/javascript` and `application/ruby`.

**Comment by rubys** [comment]
@hmdne at this point, why would anybody prefer sprockets over webpack?  Unless there is a good reason to do so, why not simply retire the sprockets code which no longer works and point people to webpack?

**Comment by hmdne** [comment]
@rubys Well, for me it's about wanting to have a Ruby-based pipeline to eg. write my own postprocessors and to have a limited number of dependencies. If someone depends on npm packages in his pipeline, I understand there is a lot less reasons to use Webpack, but I for one don't. I also think it's important to keep alternatives working to avoid monocultures.

But I don't know about this project in particular. I just found it in my GitHub feed and I decided to check it out.

**Comment by rubys** [comment]
@hdme.  Cool.  I obviously haven't kept up with the latest in sprockets; is this something that would be difficult for you to create a pull request for?  Feel free to completely replace the prior implementation as it no longer is working.

**Comment by hmdne** [comment]
@rubys I will try to find some time to do it, it would be a very good opportunity to familiarize myself with this library.

**Comment by rubys** [comment]
I've created a Sprockets 4.0 transformer: https://github.com/ruby2js/ruby2js/blob/master/lib/ruby2js/sprockets.rb , and written up an example that uses it: https://www.ruby2js.com/examples/rails/stimulus_sprockets
